export const styles={
    container:{flex:1, justifyContent:"center",alignItems:"center"},
    header:{flex:1, width:"100%",alignItems:"center",justifyContent:"center"},
    headerTitle:{fontSize:25,color:"#00cc66",fontWeight:"300"},
    clientDetailsView:{alignItems:"flex-start", paddingLeft:10},
    clientDetailsText:{fontSize:18, color:"#00cc66"},
    lstFoodHeading:{width:"100%", height:60, backgroundColor:"#00cc66", justifyContent:"center", alignItems:"flex-start"},
    lstRowView:{flexDirection:"row", justifyContent:"space-evenly"},
    lstFoodItemHeading:{flex:3,color:"#fff",fontSize:16, paddingLeft:10},
    priceHeading:{flex:2,color:"#fff",fontSize:16, paddingLeft:10},
    flatList:{flex:3,width:"100%"},
    bottomView:{height:70, flexDirection:"row", justifyContent:"space-evenly", alignItems:"center", backgroundColor:"#00cc66"},
    placeHolderButton:{width:"30%", borderWidth:2, borderColor:"#fff", borderRadius:20, justifyContent:"center",alignItems:"center"},
    placeHolderButtonText:{ marginVertical:10, color:"#fff", fontSize:18},
    TotalCostText:{  color:"#fff", fontSize:15},
}